name: ATPS
dependencies:
- openssl=1.0.2f=0
- pip=8.0.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=19.6.2=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - Bio==0.9.0
  - mne==0.23.4
  - panel==2.5.0
  - glob==0.5.1
  - shutil==0.1.3
  - matplotlib==1.5.1
  - sys==3.1
  - numpy==1.8.1
  - time==2.1.0
  - subprocess==2.4.2
  - os.path==2015.7
  - scipy.stats==3.11
