name: ATPS
dependencies:
- pip=22.3.1
- python=3.10.6
- bioconda mafft
- bioconda clustalo
- bioconda gblocks
- bioconda phyml
- bioconda phast
- bioconda java-jdk
- muscle
- pip:
  - Bio==0.9.0
  - mne==0.23.4
  - panel==2.5.0
  - glob==0.5.1
  - shutil==0.1.3
  - matplotlib==1.5.1
  - sys==3.1
  - numpy==1.8.1
  - time==2.1.0
  - subprocess==2.4.2
  - os.path==2015.7
  - scipy.stats==3.11
